cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    sarmaos:
      email: spirosarmaos@gmail.com
      failed_login_attempts: 0
      first_name: Spyros
      last_name: Armaos
      logged_in: true
      password: $2b$12$/CWgIGEjT8OzrVzQ8cYFNuxqyb7WzCn/Mz2j5WkNPzP9uA2xctwnm
      password_hint: dissertation
      roles: null
pre-authorized:
  emails: null
